version: "3.13.2"
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mappe le port 8080 du conteneur au port 8080 de l'hôte
    environment:
      - NEXT_PUBLIC_API_URL=http://back-end:5002 # URL de l'API back-end
    depends_on:
      - back-end
    networks:
      - app_network

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - KEDRO_PROJECT_PATH=/app
    volumes:
      - ./data:/app/data  # Volume partagé pour les données
      - ./conf:/app/conf  # Configuration partagée
      - ./src:/app/src    # Code source Kedro
    ports:
      - "5002:5002" # Expose l'API Flask sur le port 5002
    networks:
      - app_network

networks:
  app_network:
    driver: bridge