version: "3.13.2"
services:
  back-end:
    build:
      context: ./back-end
    container_name: back-end
    ports:
      - "5002:5002"
    volumes:
      - ./back-end:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5002
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - front-end

  front-end:
    build:
      context: ./front-end
    container_name: front-end
    ports:
      - "8080:8080"
    volumes:
      - ./front-end:/app
    working_dir: /app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5002