version: "3.13.2"
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Expose le front-end sur le port 8080
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5002 # Appelle le back-end via le réseau Docker
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - KEDRO_PROJECT_PATH=/app
    volumes:
      - ./data:/app/data  # Volume partagé pour les données
      - ./conf:/app/conf  # Configuration partagée
      - ./src:/app/src    # Code source Kedro
    ports:
      - "5002:5002" # Expose l'API Flask sur le port 5002
    networks:
      - app_network

networks:
  app_network:
    driver: bridge