version: "3.13.2"
services:
  back-end:
    image: rgojard/tp-audiogram-gb-back-end:latest
    container_name: back-end
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development

  front-end:
    image: rgojard/tp-audiogram-gb-front-end:latest
    container_name: front-end
    ports:
      - "8080:8080"
    environment:
      - NEXT_PUBLIC_API_URL=http://back-end:5002
    depends_on:
      - back-end